### ISSUE TITLE
请问如何用sketch对截图进行尺寸标注

### ISSUE THREAD

**Issue by JaynChen** [ihappyhacking/MyOne-iOS#2]
通过手机截图官方客户端后，然后用sketch对截图里的各个控件进行标注，请问你是怎么做到的？打开你的sketch文件里标注的内容，像是某个插件的自动输出，然后手工修改部分内容加以完善。可我安装了sketch，搜了些尺寸标注插件，那些插件都不能标注图片里的尺寸。

**Comment by meilbn** [comment]
额，其实我只是用 Sketch 加了那些文字而已。。。
都是手打的。。。

**Comment by JaynChen** [comment]
比如内容  VOL. 1024  怎么知道它的 字体大小：13，颜色：#555555，X：10，Y：12，H：16，颜色可以pick color，可字体大小和frame呢，总不会是凭经验估算的吧？

**Comment by meilbn** [comment]
哈，不是像素眼。。。
颜色、字体大小、frame 等等，都是用 Reveal 看的。。。
这个在 README 里面有说明。。。

**Comment by JaynChen** [comment]
刚刚我也用reveal查看了下，确实可以看到字体类型、字体大小、frame，颜色等等诸多属性，刚做开发不久，第一次听说这个软件，十分感谢你的推荐。不过reveal只能查看自己开发的app，查看手机里安装的一个官方app的各种属性好像必须越狱后配置一些东西。你是这样做的么？

**Comment by meilbn** [comment]
yup，我是越狱了之后安装了一个 reveal 的插件，可以查看第三方 app。。。

**Comment by JaynChen** [comment]
感谢你的耐心解答。我把你的3.0版本的代码用soureTree的存档功能分解成好多个部分从头一点点进行模仿学习，被reading改read折腾到了。其中_label=({UILabel *label; ...  label;}); 这种写法很高明，以前从没见过，我发现这样很好的解决了给局部变量命名的头疼问题，而且相关代码都装在一起很好看。还有3.0版本还没做完：音乐播放有显示但不能播放；短篇和连载做了头部作者相关和尾部评论，文章内容为空，问题里是有内容的；首页、文章、音乐划完10次时没有做弹出往期列表；天气暂时做的固定数据；分享登录有弹出果冻动画但没有点击事件；注册、登录、搜索、点赞、小记功能都没做完。但是代码思路逻辑清晰，难度不算很难，值得模仿学习。“我的眼里只有代码”这句话我也很喜欢，借来用用。

**Comment by meilbn** [comment]
哈。。。
reading 和 read 的问题我也纠结过，官方有些命名是 read，这个有空也顺便改成一致，最近一直加班赶项目，都没有空余时间做3.0，现在项目也快上线了，之后时间会多一点。。。
那种写法是 GCC 语法，我第一次看到也挺喜欢的。。。
短篇和连载内容我自己这边都是显示的，不知道你那边是什么情况。。。
有些功能都还没做呢。。。
天气的话，暂时没去仔细抓包，还不知道用的是什么接口，不过这个功能也不是很重要，后面慢慢做。
有些功能涉及登录的，或者分享的，都还是没有实现。。。
这个 App 难度是不大的，而且用了挺多的第三方库，基本上就是获取到数据拼凑起来，然后界面加上一些逻辑。。。
“我的眼里只有代码” 这句话好多人第一次听到都觉得挺屌的。。。
